spring:
  application:
    name: configuration-properties-config

server:
  port: 9090

user:
  email: darsh@example.com
  address:
    city: Pune
    state: Maharashtra
    country: India
  mobile:
    - 9090909090
    - 8080808080

